name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2-beta
        with:
          go-version: '^1.14.x'
      - run: go test -race -covermode atomic -coverprofile=profile.cov ./...
      - name: Send coverage
          env:
            COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            GO111MODULE=off go get github.com/mattn/goveralls
            $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github
