name: Test
on: [push, pull_request]
jobs:
  test:
    name: Smoke test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.14.x'
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          go mod download
      - name: Run smoke test
        run: |
          go test